"""
catalog_service.py — Backend aggregation service for GET /moves, /items, /abilities.

The local Pokémon Showdown data (shared/ps_data/{moves,items,abilities}.json,
generated by scripts/sync_ps_data.py) defines the canonical set of entries —
PokéAPI's own /item list in particular includes ~2100 key items, mail, etc.
that aren't relevant to a team builder, so it is not used to enumerate
entries, only to enrich the ones PS already knows about.

preload() is a one-time background task (started at app startup, same
pattern as PokemonResolverService.load_smogon_data()) that fetches PokéAPI
detail for every PS entry and merges it in. Until it completes, list_*()
methods raise 503; get_*() methods always work via a live per-request
PokéAPI fetch fallback.
"""

import asyncio
import json
import logging
import math
import os
import re
from datetime import datetime, timezone

import httpx
from fastapi import HTTPException
from sqlalchemy import func, select, text
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import AsyncSessionLocal
from app.models.catalog_cache import CatalogCache
from app.schemas.catalog import (
    AbilitiesListResponse,
    AbilityEntry,
    ItemEntry,
    ItemsListResponse,
    MoveEntry,
    MovesListResponse,
)
from app.services.learnset_service import normalize_ps_id

logger = logging.getLogger(__name__)

# Same env vars as pokemon_resolver.py — both services read shared/ps_data/ independently.
_SHARED_DIR = os.environ.get("SHARED_DIR", "../shared")
_PS_DATA_DIR = os.environ.get("PS_DATA_DIR", os.path.join(_SHARED_DIR, "ps_data"))
_POKEAPI_BASE = "https://pokeapi.co/api/v2"

# PS ability-slot key -> PokéAPI-style slot number (1, 2, 3=hidden). Same mapping
# pokemon_resolver.py uses when building AbilityInfo from pokedex.json abilities.
_PS_TO_SLOT: dict[str, int] = {"0": 1, "1": 2, "H": 3}

_SLUG_STRIP_RE = re.compile(r"[',.()\[\]]")

# The 18 universal Z-moves (one per type) whose damage class varies between
# physical and special depending on the base move used with the Z-Crystal.
# PokéAPI exposes them as <name>--physical and <name>--special, which is why
# _preload_kind detects them dynamically — but load_from_db restores from a
# cached snapshot that may pre-date that logic, so we apply the patch here too.
_Z_VARIES_NAMES: frozenset[str] = frozenset({
    "breakneck-blitz",
    "all-out-pummeling",
    "supersonic-skystrike",
    "acid-downpour",
    "tectonic-rage",
    "continental-crush",
    "savage-spin-out",
    "never-ending-nightmare",
    "corkscrew-crash",
    "inferno-overdrive",
    "hydro-vortex",
    "bloom-doom",
    "gigavolt-havoc",
    "shattered-psyche",
    "subzero-slammer",
    "devastating-drake",
    "black-hole-eclipse",
    "twinkle-tackle",
})
_NON_ALNUM_RE = re.compile(r"[^a-z0-9]")

_ROMAN_TO_GEN: dict[str, int] = {
    "i": 1, "ii": 2, "iii": 3, "iv": 4, "v": 5,
    "vi": 6, "vii": 7, "viii": 8, "ix": 9,
}


def _pokeapi_gen(pokeapi_data: dict) -> int | None:
    """Extract the introduction generation from a PokéAPI move/ability response.

    shared/ps_data/moves.json and abilities.json currently have a broken `gen`
    field (every move reports 1, every ability reports 3 — see issue #293,
    PS's raw TS source doesn't carry a `gen` key the sync script assumed
    existed). PokéAPI's own `generation` field is reliable and already fetched
    during preload, so it takes priority over the PS field for these two
    resources. Items have no equivalent PokéAPI field, but their PS `gen`
    field is already correct, so no override is needed there.
    """
    gen_name = (pokeapi_data.get("generation") or {}).get("name")
    if not gen_name:
        return None
    return _ROMAN_TO_GEN.get(gen_name.split("-")[-1])


def _ps_slug(display_name: str) -> str:
    """Best-effort PokéAPI slug from a PS display name.

    "Thunderbolt" -> "thunderbolt"; "10,000,000 Volt Thunderbolt" ->
    "10000000-volt-thunderbolt"; "King's Rock" -> "kings-rock".
    Used to query PokéAPI by name during preload; the real PokéAPI-returned
    `name` field (once fetched) becomes the entry's canonical key.
    """
    cleaned = _SLUG_STRIP_RE.sub("", display_name.lower())
    return re.sub(r"\s+", "-", cleaned.strip())


def _ps_id_from_name(name: str) -> str:
    """Collapse a name to PS's own no-separator id format, e.g. 'Sand Veil' -> 'sandveil'."""
    return _NON_ALNUM_RE.sub("", name.lower())


def _first_en_effect(effect_entries: list[dict]) -> tuple[str | None, str | None]:
    entry = next(
        (e for e in effect_entries if e.get("language", {}).get("name") == "en"), None
    )
    if entry is None:
        return None, None
    return entry.get("short_effect"), entry.get("effect")


def _paginate(seq: list, page: int, page_size: int) -> tuple[list, int, int]:
    total = len(seq)
    total_pages = max(1, math.ceil(total / page_size))
    start = (page - 1) * page_size
    return seq[start : start + page_size], total, total_pages


class CatalogService:
    def __init__(self) -> None:
        self._moves_ps: dict[str, dict] = {}
        self._items_ps: dict[str, dict] = {}
        self._abilities_ps: dict[str, dict] = {}
        self._pokedex: dict[str, dict] = {}
        # PS species dex number -> ps_id (first entry wins; base forms only —
        # does not cover extended PokéAPI variety ids like 10034).
        self._num_to_ps_id: dict[int, str] = {}

        self._moves: dict[str, MoveEntry] = {}
        self._items: dict[str, ItemEntry] = {}
        self._abilities: dict[str, AbilityEntry] = {}
        self._moves_by_id: dict[int, str] = {}
        self._items_by_id: dict[int, str] = {}
        self._abilities_by_id: dict[int, str] = {}
        self._loaded = False

        self._pokeapi_http = httpx.AsyncClient(
            timeout=10.0, limits=httpx.Limits(max_connections=100)
        )
        self._semaphore = asyncio.Semaphore(20)

    # ------------------------------------------------------------------
    # Startup loading
    # ------------------------------------------------------------------

    def load_ps_data(self) -> None:
        """Load PS data files from disk into memory. Called synchronously at startup."""
        for fname, attr in [
            ("moves.json", "_moves_ps"),
            ("items.json", "_items_ps"),
            ("abilities.json", "_abilities_ps"),
            ("pokedex.json", "_pokedex"),
        ]:
            path = os.path.join(_PS_DATA_DIR, fname)
            if os.path.exists(path):
                with open(path, encoding="utf-8") as f:
                    setattr(self, attr, json.load(f))
                logger.info("CatalogService loaded %s (%d entries)", fname, len(getattr(self, attr)))
            else:
                logger.warning("%s not found — run scripts/sync_ps_data.py", fname)

        for ps_id, entry in self._pokedex.items():
            num = entry.get("num")
            if num is not None and num not in self._num_to_ps_id:
                self._num_to_ps_id[num] = ps_id

    async def preload(self) -> None:
        """Fetch PokéAPI detail for every PS move/item/ability and merge it in.

        One-time background task, same idea as PokemonResolverService.load_smogon_data().
        list_moves/list_items/list_abilities raise 503 until this completes.
        """
        logger.info(
            "Starting catalog preload (%d moves, %d items, %d abilities)…",
            len(self._moves_ps), len(self._items_ps), len(self._abilities_ps),
        )
        await self._preload_kind("move", self._moves_ps, self._merge_move, self._moves, self._moves_by_id)
        await self._preload_kind("item", self._items_ps, self._merge_item, self._items, self._items_by_id)
        await self._preload_kind("ability", self._abilities_ps, self._merge_ability, self._abilities, self._abilities_by_id)
        self._loaded = True
        logger.info(
            "Catalog preload complete: %d moves, %d items, %d abilities",
            len(self._moves), len(self._items), len(self._abilities),
        )

    async def _preload_kind(
        self, kind: str, ps_dict: dict[str, dict], merge_fn, target: dict, id_map: dict[int, str],
    ) -> None:
        # Enumerate from PokéAPI first — this is the authoritative source for
        # which entries exist.  PS data is used as enrichment, not enumeration.
        names = await self._fetch_pokeapi_names(kind)
        if not names:
            # PokéAPI list unavailable — fall back to PS-only enumeration.
            for ps_id, raw in ps_dict.items():
                entry = merge_fn(ps_id, raw, None)
                target[entry.name] = entry
            logger.warning(
                "Catalog preload: %s — PokéAPI list unavailable; built %d entries from PS data only",
                kind, len(ps_dict),
            )
            return

        # For moves: collect base names that have --physical/--special variants.
        # These are universal Z-moves whose damage class genuinely varies.
        z_varies: set[str] = set()
        if kind == "move":
            for name in names:
                m = re.match(r"^(.+)--(?:physical|special)$", name)
                if m:
                    z_varies.add(m.group(1))

        # Fetch PokéAPI detail for every name concurrently.
        responses = await asyncio.gather(
            *[self._fetch_pokeapi_resource(kind, name) for name in names]
        )

        # Merge each PokéAPI entry with its PS counterpart (if any).
        covered_ps_ids: set[str] = set()
        count = ps_matched = 0
        for name, pokeapi_data in zip(names, responses):
            if pokeapi_data is None:
                continue
            canonical_name = pokeapi_data.get("name", name)
            # Strip PokéAPI variant suffixes that don't appear in PS:
            #   items: --held, --bag (e.g. normalium-z--held → normalium-z)
            #   moves: --physical, --special (e.g. all-out-pummeling--physical)
            if kind in ("item", "move"):
                canonical_name = re.sub(r"--\w+$", "", canonical_name)
            if canonical_name in target:
                continue  # deduplicate --held / --bag variants of the same item
            ps_id = _ps_id_from_name(canonical_name)
            covered_ps_ids.add(ps_id)
            if ps_id in ps_dict:
                ps_matched += 1
            raw = ps_dict.get(ps_id, {
                "name": canonical_name.replace("-", " ").title(),
                "gen": 1,
            })
            entry = merge_fn(ps_id, raw, pokeapi_data)
            target[entry.name] = entry
            if "id" in pokeapi_data:
                id_map[pokeapi_data["id"]] = entry.name
            count += 1

        # Add PS-only entries with no PokéAPI page (Z-moves, Max moves, etc.)
        ps_only = 0
        for ps_id, raw in ps_dict.items():
            if ps_id not in covered_ps_ids:
                entry = merge_fn(ps_id, raw, None)
                if entry.name not in target:
                    target[entry.name] = entry
                    ps_only += 1

        # Universal Z-moves that have --physical and --special PokéAPI variants
        # can act as either damage class depending on the base move used.
        for base_name in z_varies:
            entry = target.get(base_name)
            if entry is not None:
                target[base_name] = entry.model_copy(update={"damage_class": "varies"})

        logger.info(
            "Catalog preload: %s — %d PokéAPI entries (%d with PS enrichment) + %d PS-only (%d varies)",
            kind, count, ps_matched, ps_only, len(z_varies),
        )

    async def _fetch_pokeapi_names(self, kind: str) -> list[str]:
        """Fetch the full name list for a PokéAPI resource kind (e.g. all move names)."""
        try:
            r = await self._pokeapi_http.get(
                f"{_POKEAPI_BASE}/{kind}", params={"limit": 100_000, "offset": 0}
            )
        except Exception:
            return []
        if r.status_code != 200:
            return []
        return [e["name"] for e in r.json().get("results", [])]

    async def _fetch_pokeapi_resource(self, kind: str, id_or_name: str) -> dict | None:
        async with self._semaphore:
            try:
                r = await self._pokeapi_http.get(f"{_POKEAPI_BASE}/{kind}/{id_or_name}")
            except Exception:
                return None
        if r.status_code != 200:
            return None
        return r.json()

    # ------------------------------------------------------------------
    # PS + PokéAPI merge
    # ------------------------------------------------------------------

    def _merge_move(self, ps_id: str, raw: dict, pokeapi_data: dict | None) -> MoveEntry:
        display_name = raw.get("name", ps_id)
        slug = _ps_slug(display_name)
        damage_class = (raw.get("category") or "status").lower()
        gen = raw.get("gen", 1)
        contest_type = target = effect_short = effect = None
        # PS is preferred for battle stats; PokéAPI used as fallback for
        # entries that exist on PokéAPI but have no PS data.
        type_ = raw.get("type")
        power = raw.get("base_power")
        accuracy = raw.get("accuracy")
        pp = raw.get("pp")
        priority = raw.get("priority", 0)

        if pokeapi_data is not None:
            # Strip --physical / --special variant suffixes so all variants of
            # a Z-move resolve to the same canonical name as the PS entry.
            raw_name = pokeapi_data.get("name", slug)
            slug = re.sub(r"--\w+$", "", raw_name)
            damage_class = (pokeapi_data.get("damage_class") or {}).get("name") or damage_class
            gen = _pokeapi_gen(pokeapi_data) or gen
            contest_type = (pokeapi_data.get("contest_type") or {}).get("name")
            target = (pokeapi_data.get("target") or {}).get("name")
            effect_short, effect = _first_en_effect(pokeapi_data.get("effect_entries", []))
            effect_chance = pokeapi_data.get("effect_chance")
            if effect and effect_chance is not None:
                effect = effect.replace("$effect_chance", str(effect_chance))
            if type_ is None:
                type_ = (pokeapi_data.get("type") or {}).get("name")
            if power is None:
                power = pokeapi_data.get("power")
            if accuracy is None:
                accuracy = pokeapi_data.get("accuracy")
            if pp is None:
                pp = pokeapi_data.get("pp")
            if not priority:
                priority = pokeapi_data.get("priority") or 0

        if not type_:
            type_ = "normal"

        # Z-moves and Max/G-Max moves are tied to a single generation by game
        # mechanics (Z-moves: gen 7 only; Max moves: gen 8 only — neither
        # mechanic gained new moves after its introducing generation). This is
        # more reliable than PokéAPI's generation field, which many Z-moves and
        # Max moves don't even have a resource for (404) — those would
        # otherwise fall through to the broken PS default (see issue #293).
        if raw.get("is_z_move"):
            gen = 7
        elif raw.get("is_max_move"):
            gen = 8

        # raw["z_move_base"] is a PS no-separator id (e.g. "volttackle") — convert
        # to the same hyphenated PokéAPI-style slug used everywhere else (e.g.
        # "volt-tackle") so it can be passed straight to GET /moves/{id_or_name}.
        z_move_base_ps_id = raw.get("z_move_base")
        z_move_base = None
        if z_move_base_ps_id:
            base_raw = self._moves_ps.get(z_move_base_ps_id)
            z_move_base = _ps_slug(base_raw["name"]) if base_raw else z_move_base_ps_id

        pokeapi_id = pokeapi_data.get("id") if pokeapi_data is not None else None

        return MoveEntry(
            id=pokeapi_id,
            name=slug,
            display_name=display_name,
            gen=gen,
            type=type_,
            damage_class=damage_class,
            power=power,
            accuracy=accuracy,
            pp=pp,
            priority=priority,
            is_z_move=raw.get("is_z_move", False),
            is_max_move=raw.get("is_max_move", False),
            z_move_base=z_move_base,
            flags=raw.get("flags") or {},
            secondary=raw.get("secondary"),
            contest_type=contest_type,
            target=target,
            effect_short=effect_short,
            effect=effect,
        )

    def _merge_item(self, ps_id: str, raw: dict, pokeapi_data: dict | None) -> ItemEntry:
        display_name = raw.get("name", ps_id)
        slug = _ps_slug(display_name)
        category = sprite = None
        fling_power = None
        effect_short = effect = None

        if pokeapi_data is not None:
            # Strip PokéAPI variant suffixes (--held, --bag) — the canonical
            # catalog key is "normalium-z", not "normalium-z--held".
            raw_name = pokeapi_data.get("name", slug)
            slug = re.sub(r"--\w+$", "", raw_name)
            category = (pokeapi_data.get("category") or {}).get("name")
            sprite = (pokeapi_data.get("sprites") or {}).get("default")
            fling_power = pokeapi_data.get("fling_power")
            effect_short, effect = _first_en_effect(pokeapi_data.get("effect_entries", []))

        return ItemEntry(
            name=slug,
            display_name=display_name,
            gen=raw.get("gen", 1),
            category=category,
            sprite=sprite,
            fling_power=fling_power,
            is_mega_stone=raw.get("is_mega_stone", False),
            mega_species=raw.get("mega_species"),
            is_z_crystal=raw.get("is_z_crystal", False),
            is_berry=raw.get("is_berry", False),
            is_plate=raw.get("is_plate", False),
            is_memory=raw.get("is_memory", False),
            effect_short=effect_short,
            effect=effect,
        )

    def _merge_ability(self, ps_id: str, raw: dict, pokeapi_data: dict | None) -> AbilityEntry:
        display_name = raw.get("name", ps_id)
        slug = _ps_slug(display_name)
        gen = raw.get("gen", 1)
        effect_short = effect = None

        if pokeapi_data is not None:
            slug = pokeapi_data.get("name", slug)
            gen = _pokeapi_gen(pokeapi_data) or gen
            effect_short, effect = _first_en_effect(pokeapi_data.get("effect_entries", []))

        return AbilityEntry(
            name=slug,
            display_name=display_name,
            gen=gen,
            effect_short=effect_short,
            effect=effect,
        )

    # ------------------------------------------------------------------
    # List endpoints
    # ------------------------------------------------------------------

    def list_moves(
        self, page: int, page_size: int, *,
        gen: int | None = None, damage_class: str | None = None, contest_type: str | None = None,
        is_z_move: bool | None = None, is_max_move: bool | None = None,
    ) -> MovesListResponse:
        if not self._loaded:
            raise HTTPException(503, detail="Move catalog is still loading; try again shortly")
        values = list(self._moves.values())
        if gen is not None:
            values = [m for m in values if m.gen == gen]
        if damage_class is not None:
            values = [m for m in values if m.damage_class == damage_class]
        if contest_type is not None:
            values = [m for m in values if m.contest_type == contest_type]
        if is_z_move is not None:
            values = [m for m in values if m.is_z_move == is_z_move]
        if is_max_move is not None:
            values = [m for m in values if m.is_max_move == is_max_move]
        values.sort(key=lambda m: m.name)
        page_items, total, total_pages = _paginate(values, page, page_size)
        return MovesListResponse(items=page_items, total=total, page=page, page_size=page_size, total_pages=total_pages)

    def list_items(
        self, page: int, page_size: int, *,
        gen: int | None = None, category: str | None = None,
        is_mega_stone: bool | None = None, is_z_crystal: bool | None = None,
        is_berry: bool | None = None, is_plate: bool | None = None, is_memory: bool | None = None,
    ) -> ItemsListResponse:
        if not self._loaded:
            raise HTTPException(503, detail="Item catalog is still loading; try again shortly")
        values = list(self._items.values())
        if gen is not None:
            values = [i for i in values if i.gen == gen]
        if category is not None:
            values = [i for i in values if i.category == category]
        if is_mega_stone is not None:
            values = [i for i in values if i.is_mega_stone == is_mega_stone]
        if is_z_crystal is not None:
            values = [i for i in values if i.is_z_crystal == is_z_crystal]
        if is_berry is not None:
            values = [i for i in values if i.is_berry == is_berry]
        if is_plate is not None:
            values = [i for i in values if i.is_plate == is_plate]
        if is_memory is not None:
            values = [i for i in values if i.is_memory == is_memory]
        values.sort(key=lambda i: i.name)
        page_items, total, total_pages = _paginate(values, page, page_size)
        return ItemsListResponse(items=page_items, total=total, page=page, page_size=page_size, total_pages=total_pages)

    def list_abilities(
        self, page: int, page_size: int, *, gen: int | None = None, pokemon: str | None = None,
    ) -> AbilitiesListResponse:
        if pokemon is not None:
            entries = self._abilities_for_pokemon(pokemon)
            return AbilitiesListResponse(
                items=entries, total=len(entries), page=1, page_size=max(len(entries), 1), total_pages=1,
            )
        if not self._loaded:
            raise HTTPException(503, detail="Ability catalog is still loading; try again shortly")
        values = list(self._abilities.values())
        if gen is not None:
            values = [a for a in values if a.gen == gen]
        values.sort(key=lambda a: a.name)
        page_items, total, total_pages = _paginate(values, page, page_size)
        return AbilitiesListResponse(items=page_items, total=total, page=page, page_size=page_size, total_pages=total_pages)

    def _resolve_pokemon_ps_id(self, pokemon: str) -> str | None:
        if pokemon.isdigit():
            return self._num_to_ps_id.get(int(pokemon))
        for candidate in normalize_ps_id(pokemon):
            if candidate in self._pokedex:
                return candidate
        return None

    def _abilities_for_pokemon(self, pokemon: str) -> list[AbilityEntry]:
        ps_id = self._resolve_pokemon_ps_id(pokemon)
        if ps_id is None:
            raise HTTPException(404, detail=f"Pokémon '{pokemon}' not found")
        abilities_raw: dict[str, str] = self._pokedex.get(ps_id, {}).get("abilities", {})
        result: list[AbilityEntry] = []
        for key, ability_name in abilities_raw.items():
            slot = _PS_TO_SLOT.get(key, 1)
            is_hidden = key == "H"
            ability_ps_id = _ps_id_from_name(ability_name)
            entry = self._abilities.get(_ps_slug(ability_name))
            if entry is None:
                raw = self._abilities_ps.get(ability_ps_id, {"name": ability_name, "gen": 1})
                entry = self._merge_ability(ability_ps_id, raw, None)
            result.append(entry.model_copy(update={"slot": slot, "is_hidden": is_hidden}))
        return result

    # ------------------------------------------------------------------
    # Single-entry endpoints (always available — live PokéAPI fallback)
    # ------------------------------------------------------------------

    async def get_move(self, id_or_name: str) -> MoveEntry:
        return await self._get_entry("move", id_or_name, self._moves, self._moves_by_id, self._moves_ps, self._merge_move)

    async def get_item(self, id_or_name: str) -> ItemEntry:
        return await self._get_entry("item", id_or_name, self._items, self._items_by_id, self._items_ps, self._merge_item)

    async def get_ability(self, id_or_name: str) -> AbilityEntry:
        return await self._get_entry("ability", id_or_name, self._abilities, self._abilities_by_id, self._abilities_ps, self._merge_ability)

    async def _get_entry(
        self, kind: str, id_or_name: str,
        catalog: dict[str, "MoveEntry | ItemEntry | AbilityEntry"], id_map: dict[int, str],
        ps_dict: dict[str, dict], merge_fn,
    ):
        if id_or_name.isdigit():
            slug = id_map.get(int(id_or_name))
            if slug is not None and slug in catalog:
                return catalog[slug]
        elif id_or_name in catalog:
            return catalog[id_or_name]

        # Not in the (possibly still-loading) in-memory catalog — fetch live.
        # PokéAPI accepts both name and numeric id at this path directly.
        pokeapi_data = await self._fetch_pokeapi_resource(kind, id_or_name)
        if pokeapi_data is not None:
            canonical_name = pokeapi_data.get("name", id_or_name)
            if kind in ("item", "move"):
                canonical_name = re.sub(r"--\w+$", "", canonical_name)
            ps_id = canonical_name.replace("-", "").lower()
            raw = ps_dict.get(ps_id, {"name": canonical_name.replace("-", " ").title(), "gen": 1})
        else:
            ps_id = _ps_id_from_name(id_or_name)
            raw = ps_dict.get(ps_id)
            if raw is None:
                raise HTTPException(404, detail=f"{kind.capitalize()} '{id_or_name}' not found")

        entry = merge_fn(ps_id, raw, pokeapi_data)
        catalog[entry.name] = entry  # backfill so subsequent lookups hit the fast path
        if pokeapi_data is not None and "id" in pokeapi_data:
            id_map[pokeapi_data["id"]] = entry.name
        return entry

    # ------------------------------------------------------------------
    # PostgreSQL DB caching
    # ------------------------------------------------------------------

    async def load_from_db(self, db: AsyncSession) -> bool:
        """Load catalog from the DB cache if all three kinds have fresh entries.

        Returns True and sets _loaded=True if the full catalog was restored;
        returns False if any kind is absent or expired (caller should preload).
        """
        try:
            result = await db.execute(
                select(CatalogCache).where(
                    CatalogCache.fetched_at + text("(ttl_days * interval '1 day')") > func.now()
                )
            )
            rows = result.scalars().all()
        except Exception as exc:
            logger.warning("Failed to load catalog from DB — falling back to PokéAPI preload: %s", exc)
            return False

        if not rows:
            return False

        kind_counts: dict[str, int] = {"move": 0, "item": 0, "ability": 0}
        for row in rows:
            if row.kind == "move":
                try:
                    self._moves[row.name] = MoveEntry.model_validate(row.data)
                except Exception:
                    continue
                if row.pokeapi_id is not None:
                    self._moves_by_id[row.pokeapi_id] = row.name
                kind_counts["move"] += 1
            elif row.kind == "item":
                try:
                    self._items[row.name] = ItemEntry.model_validate(row.data)
                except Exception:
                    continue
                if row.pokeapi_id is not None:
                    self._items_by_id[row.pokeapi_id] = row.name
                kind_counts["item"] += 1
            elif row.kind == "ability":
                try:
                    self._abilities[row.name] = AbilityEntry.model_validate(row.data)
                except Exception:
                    continue
                if row.pokeapi_id is not None:
                    self._abilities_by_id[row.pokeapi_id] = row.name
                kind_counts["ability"] += 1

        if all(kind_counts[k] > 0 for k in ("move", "item", "ability")):
            # Ensure universal Z-moves have damage_class="varies" regardless of
            # what was stored — DB snapshots pre-dating this logic have "physical".
            for name in _Z_VARIES_NAMES:
                if name in self._moves:
                    self._moves[name] = self._moves[name].model_copy(
                        update={"damage_class": "varies"}
                    )
            self._loaded = True
            logger.info(
                "Catalog loaded from DB cache: %d moves, %d items, %d abilities",
                kind_counts["move"], kind_counts["item"], kind_counts["ability"],
            )
            return True

        # Partial load — clear what we've written and fall back to PokéAPI preload.
        self._moves.clear()
        self._items.clear()
        self._abilities.clear()
        self._moves_by_id.clear()
        self._items_by_id.clear()
        self._abilities_by_id.clear()
        logger.info(
            "Catalog DB cache incomplete (move=%d item=%d ability=%d) — falling back to PokéAPI preload",
            kind_counts["move"], kind_counts["item"], kind_counts["ability"],
        )
        return False

    async def _persist_to_db(self, db: AsyncSession) -> None:
        """Batch-upsert all in-memory catalog entries to catalog_cache."""
        move_id_for = {v: k for k, v in self._moves_by_id.items()}
        item_id_for = {v: k for k, v in self._items_by_id.items()}
        ability_id_for = {v: k for k, v in self._abilities_by_id.items()}

        now = datetime.now(timezone.utc)
        rows: list[dict] = []
        for name, entry in self._moves.items():
            rows.append({
                "kind": "move", "name": name,
                "pokeapi_id": move_id_for.get(name),
                "data": entry.model_dump(mode="json"),
                "fetched_at": now, "ttl_days": 7,
            })
        for name, entry in self._items.items():
            rows.append({
                "kind": "item", "name": name,
                "pokeapi_id": item_id_for.get(name),
                "data": entry.model_dump(mode="json"),
                "fetched_at": now, "ttl_days": 7,
            })
        for name, entry in self._abilities.items():
            rows.append({
                "kind": "ability", "name": name,
                "pokeapi_id": ability_id_for.get(name),
                "data": entry.model_dump(mode="json"),
                "fetched_at": now, "ttl_days": 7,
            })

        if not rows:
            return

        try:
            _CHUNK = 500
            for i in range(0, len(rows), _CHUNK):
                chunk = rows[i : i + _CHUNK]
                stmt = pg_insert(CatalogCache).values(chunk)
                stmt = stmt.on_conflict_do_update(
                    index_elements=["kind", "name"],
                    set_={
                        "pokeapi_id": stmt.excluded.pokeapi_id,
                        "data": stmt.excluded.data,
                        "fetched_at": stmt.excluded.fetched_at,
                    },
                )
                await db.execute(stmt)
            await db.commit()
            logger.info("Catalog persisted to DB: %d rows", len(rows))
        except Exception as exc:
            logger.error("Failed to persist catalog to DB: %s", exc)

    async def preload_and_persist(self) -> None:
        """Run PokéAPI preload then persist results to DB. Safe to use as asyncio.create_task()."""
        await self.preload()
        async with AsyncSessionLocal() as db:
            await self._persist_to_db(db)

    def evict(self, kinds: list[str] | None = None) -> None:
        """Clear in-memory catalog for the given kinds (or all if kinds is None).

        Called after DELETE /admin/cache/catalog so the next preload_and_persist()
        starts from scratch rather than re-persisting stale in-memory state.
        """
        targets = kinds if kinds is not None else ["move", "item", "ability"]
        for kind in targets:
            if kind == "move":
                self._moves.clear()
                self._moves_by_id.clear()
            elif kind == "item":
                self._items.clear()
                self._items_by_id.clear()
            elif kind == "ability":
                self._abilities.clear()
                self._abilities_by_id.clear()
        if not self._moves or not self._items or not self._abilities:
            self._loaded = False


catalog_service = CatalogService()
