// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7lyjfVIiOFjQOxeaMwLarWgSFiiCV2k',
    appId: '1:854467000036:web:6b391b2b169c1611565ef1',
    messagingSenderId: '854467000036',
    projectId: 'poketeamdex',
    authDomain: 'poketeamdex.firebaseapp.com',
    storageBucket: 'poketeamdex.firebasestorage.app',
    measurementId: 'G-54NRV0SV40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg4gf1-sU0F2rN-onMRVGMB37m04NJWpo',
    appId: '1:854467000036:android:1dce8542b7afe7d4565ef1',
    messagingSenderId: '854467000036',
    projectId: 'poketeamdex',
    storageBucket: 'poketeamdex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHsYd8pI3eq3n4n1hvopEBY4Wy2zLP60',
    appId: '1:854467000036:ios:4b09497d83f47706565ef1',
    messagingSenderId: '854467000036',
    projectId: 'poketeamdex',
    storageBucket: 'poketeamdex.firebasestorage.app',
    iosBundleId: 'com.asante.pokeTeamDex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHsYd8pI3eq3n4n1hvopEBY4Wy2zLP60',
    appId: '1:854467000036:ios:4b09497d83f47706565ef1',
    messagingSenderId: '854467000036',
    projectId: 'poketeamdex',
    storageBucket: 'poketeamdex.firebasestorage.app',
    iosBundleId: 'com.asante.pokeTeamDex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg7lyjfVIiOFjQOxeaMwLarWgSFiiCV2k',
    appId: '1:854467000036:web:8cd399af5fd19181565ef1',
    messagingSenderId: '854467000036',
    projectId: 'poketeamdex',
    authDomain: 'poketeamdex.firebaseapp.com',
    storageBucket: 'poketeamdex.firebasestorage.app',
    measurementId: 'G-JGDMRNPDR1',
  );
}
