"""
catalog.py — Schemas for the standalone /moves, /items, /abilities catalog endpoints.

Each entry consolidates the local Pokémon Showdown data (shared/ps_data/*.json,
generated by scripts/sync_ps_data.py) with PokéAPI enrichment fetched by
CatalogService. PokéAPI-only fields (contest_type, effect text, category,
fling_power, sprite) are nullable — they stay null when PokéAPI has no
matching resource for a PS entry, or before CatalogService.preload() has
merged them in.
"""

from pydantic import BaseModel


class MoveEntry(BaseModel):
    id: int | None = None              # PokéAPI numeric ID — use this for /move/{id} lookups
    name: str                          # PokéAPI slug, e.g. "thunderbolt"
    display_name: str                  # PS display name, e.g. "Thunderbolt"
    gen: int
    type: str
    damage_class: str                  # "physical" | "special" | "status" | "varies"
    power: int | None = None
    accuracy: int | None = None
    pp: int | None = None
    priority: int = 0
    is_z_move: bool = False
    is_max_move: bool = False
    z_move_base: str | None = None     # base move slug, only for signature Z-crystals (17 of 35)
    flags: dict[str, int] = {}
    secondary: dict | None = None
    contest_type: str | None = None    # PokéAPI-only
    target: str | None = None          # PokéAPI-only
    effect_short: str | None = None    # PokéAPI-only
    effect: str | None = None          # PokéAPI-only, $effect_chance substituted


class ItemEntry(BaseModel):
    id: int | None = None              # PokéAPI numeric ID
    name: str
    display_name: str
    gen: int
    category: str | None = None        # PokéAPI-only
    sprite: str | None = None          # PokéAPI-only
    fling_power: int | None = None     # PokéAPI-only
    is_mega_stone: bool = False
    mega_species: dict[str, str] | None = None
    is_z_crystal: bool = False
    is_berry: bool = False
    is_plate: bool = False
    is_memory: bool = False
    effect_short: str | None = None    # PokéAPI-only
    effect: str | None = None          # PokéAPI-only


class AbilityEntry(BaseModel):
    id: int | None = None              # PokéAPI numeric ID
    name: str
    display_name: str
    gen: int
    effect_short: str | None = None    # PokéAPI-only
    effect: str | None = None          # PokéAPI-only
    slot: int | None = None            # set only via ?pokemon= filter: 1, 2, or 3 (hidden)
    is_hidden: bool = False            # only meaningful alongside slot


class MovesListResponse(BaseModel):
    items: list[MoveEntry]
    total: int
    page: int
    page_size: int
    total_pages: int


class ItemsListResponse(BaseModel):
    items: list[ItemEntry]
    total: int
    page: int
    page_size: int
    total_pages: int


class AbilitiesListResponse(BaseModel):
    items: list[AbilityEntry]
    total: int
    page: int
    page_size: int
    total_pages: int
